// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3zC2eihlPnKc0nsrji-aNWdBVzhKfUBI',
    appId: '1:566060845931:web:c6b5d08cf217bbed245a2e',
    messagingSenderId: '566060845931',
    projectId: 'moltaqa-4ee70',
    authDomain: 'moltaqa-4ee70.firebaseapp.com',
    storageBucket: 'moltaqa-4ee70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHYmGsH0qcsXNu4m-TSDNPiEOXpvKpDjI',
    appId: '1:566060845931:android:aaf28ba9d77b7017245a2e',
    messagingSenderId: '566060845931',
    projectId: 'moltaqa-4ee70',
    storageBucket: 'moltaqa-4ee70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMW_KEbMzXtBeRWAu5h0vdQg1m2j5IYo',
    appId: '1:566060845931:ios:ceb7e523a96b9ff9245a2e',
    messagingSenderId: '566060845931',
    projectId: 'moltaqa-4ee70',
    storageBucket: 'moltaqa-4ee70.firebasestorage.app',
    iosBundleId: 'com.example.moltaqa',
  );
}
